/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Definimos que el sidebar se genere automáticamente basado en la carpeta 'docs'
  mambSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Esto le dice: "toma todo lo que esté dentro de la carpeta docs"
    },
  ],
};

module.exports = sidebars;